#!/bin/bash

inputs=( 
  'Virtual core pointer'
  'Virtual core XTEST pointer'
  'TPPS/2 IBM TrackPoint'
  'SynPS/2 Synaptics TouchPad' 
  'Wacom ISDv4 E6 Finger touch'
)

wacoms=(
  'Wacom ISDv4 E6 Pen stylus' 
  'Wacom ISDv4 E6 Pen eraser'
)

declare -A direction
direction[normal]=0
direction[left]=3
direction[inverted]=2
direction[right]=1

left='0 -1 1 1 0 0 0 0 1'
right='0 1 0 -1 0 1 0 0 1'
normal='1 0 0 0 1 0 0 0 1'
inverted='-1 0 1 0 -1 1 0 0 1'

for input in "${inputs[@]}"; do
  xrandr -o $1
  xinput set-prop "$input" 'Coordinate Transformation Matrix' ${!1}
done

for wacom in "${wacoms[@]}"; do
  xsetwacom set "$wacom" Rotate $direction[$1]
done
           